# -*- coding: utf-8 -*-
"""mlpp_final_review3 (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DKtCYIYr0BnDdZS6uYhs81h5I3GwGjO9

# 🌿 Urban Pollution Hotspot Identification & Green Infrastructure Recommendation

**Objective:** Classify geographic areas into pollution zones (Low / Medium / High) using air quality sensor readings, then recommend targeted green infrastructure solutions.

**Pipeline Overview:**
1. Data Loading & Inspection
2. Data Preprocessing
3. Feature Engineering
4. Exploratory Data Analysis (EDA)
5. Target Variable Creation
6. Feature Scaling & Train-Test Split
7. Baseline ML Models (Logistic Regression, Decision Tree, KNN)
8. Ensemble Learning (Random Forest + Gradient Boosting)
9. Deep Learning — TabNet
10. Full Model Comparison
11. Green Infrastructure Recommendation System

## 1. Data Loading & Initial Inspection
"""

import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

df = pd.read_excel(r"C:\Users\bhava\Desktop\pollution-hotspot-ml\data\MLfeb8.xlsx")

print("Shape:", df.shape)
print("\nFirst 5 rows:")
print(df.head())
print("\nData Types & Null Counts:")
df.info()

"""## 2. Data Preprocessing

### 2.1 Convert Pollutant Columns to Numeric
"""

pollutant_cols = ["SO2", "NO2", "CO", "PM2.5", "PM10", "AQIValue"]

for col in pollutant_cols:
    df[col] = pd.to_numeric(df[col], errors="coerce")

print("Null counts after conversion:")
print(df[pollutant_cols].isnull().sum())

"""### 2.2 Handle Missing Values (Mean Imputation)"""

for col in pollutant_cols:
    df[col] = df[col].fillna(df[col].mean())

print("Null counts after imputation:")
print(df[pollutant_cols].isnull().sum())

"""### 2.3 Parse Dates & Extract Date Features"""

df["Date"] = pd.to_datetime(df["Date"], dayfirst=True)

df["year"]    = df["Date"].dt.year
df["month"]   = df["Date"].dt.month
df["day"]     = df["Date"].dt.day
df["weekday"] = df["Date"].dt.weekday

if df["year"].nunique() == 1:
    df = df.drop("year", axis=1)
    print("'year' dropped — only one unique value found.")

print(df[["month", "day", "weekday"]].head())

"""### 2.4 Label Encoding for Prominent Pollutant"""

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
if "ProminentPollutant" in df.columns:
    df["ProminentPollutant_encoded"] = le.fit_transform(df["ProminentPollutant"].astype(str))
    print("ProminentPollutant classes:", le.classes_)

"""## 3. Feature Engineering

### 3.1 Composite Pollution Index

A weighted combination of pollutants that captures overall air quality load. PM2.5 carries the highest weight as it poses the greatest health risk.
"""

df["Pollution_Index"] = (
    df["PM2.5"] * 0.4 +
    df["PM10"]  * 0.3 +
    df["NO2"]   * 0.1 +
    df["SO2"]   * 0.1 +
    df["CO"]    * 0.1
)

print("Pollution_Index stats:")
print(df["Pollution_Index"].describe())

"""## 4. Exploratory Data Analysis (EDA)

### 4.1 Correlation Heatmap
"""

import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(12, 10))
sns.heatmap(
    df.corr(numeric_only=True),
    annot=True, cmap="coolwarm", fmt=".2f"
)
plt.title("Correlation Matrix (All Numeric Features)")
plt.tight_layout()
plt.show()

"""### 4.2 Feature Correlation with AQI"""

corr_aqi = df.corr(numeric_only=True)["AQIValue"].drop("AQIValue").sort_values()

plt.figure(figsize=(8, 6))
colors = ["#d73027" if v > 0 else "#4575b4" for v in corr_aqi]
corr_aqi.plot(kind="barh", color=colors)
plt.axvline(0, color="black", linewidth=0.8)
plt.title("Feature Correlation with AQI Value")
plt.xlabel("Pearson Correlation")
plt.tight_layout()
plt.show()

"""### 4.3 AQI Distribution"""

plt.figure(figsize=(8, 4))
sns.histplot(df["AQIValue"], bins=40, kde=True, color="steelblue")
plt.title("Distribution of AQI Values")
plt.xlabel("AQI Value")
plt.tight_layout()
plt.show()

print(df["AQIValue"].describe())

"""## 5. Target Variable Creation

> ⚠️ **Important:** `Pollution_Zone` is created from **raw (unscaled) AQI** using the 33rd and 66th percentiles as thresholds. Scaling happens *after* this step to keep the bins interpretable.
"""

# Outlier clipping using IQR
for col in ["PM2.5", "PM10", "NO2", "AQIValue"]:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    df[col] = df[col].clip(Q1 - 1.5 * IQR, Q3 + 1.5 * IQR)

print("AQI range after clipping:", df["AQIValue"].min(), "–", df["AQIValue"].max())

low_cut  = df["AQIValue"].quantile(0.33)
high_cut = df["AQIValue"].quantile(0.66)

print(f"\nBin thresholds — Low < {low_cut:.1f} | Medium: {low_cut:.1f}–{high_cut:.1f} | High > {high_cut:.1f}")

df["Pollution_Zone"] = pd.cut(
    df["AQIValue"],
    bins=[df["AQIValue"].min() - 1, low_cut, high_cut, df["AQIValue"].max()],
    labels=["Low", "Medium", "High"],
    include_lowest=True
)

print("\nClass distribution:")
print(df["Pollution_Zone"].value_counts())

plt.figure(figsize=(6, 4))
df["Pollution_Zone"].value_counts().plot(
    kind="bar", color=["#2ecc71", "#f39c12", "#e74c3c"]
)
plt.title("Pollution Zone Class Distribution")
plt.xlabel("Zone")
plt.ylabel("Count")
plt.xticks(rotation=0)
plt.tight_layout()
plt.show()

"""## 6. Feature Selection, Scaling & Train-Test Split

### 6.1 Drop Low-Impact & Redundant Features
"""

cols_to_drop = ["ProminentPollutant_encoded", "ProminentPollutant", "CO", "SO2", "Date"]
df = df.drop(cols_to_drop, axis=1, errors="ignore")

print("Remaining columns:", list(df.columns))

"""### 6.2 Define Features & Target"""

features = ["PM2.5", "PM10", "NO2", "Pollution_Index", "lat", "long", "month"]
features = [f for f in features if f in df.columns]
print("Selected features:", features)

df_clean = df.dropna(subset=features + ["Pollution_Zone"]).copy()
print(f"\nRows before cleaning: {len(df)} | After cleaning: {len(df_clean)}")

X = df_clean[features]
y = df_clean["Pollution_Zone"]

"""### 6.3 Train-Test Split (before scaling to prevent data leakage)"""

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

print(f"Training samples: {len(X_train)} | Test samples: {len(X_test)}")
print("\nClass balance in train:")
print(y_train.value_counts())

"""### 6.4 Feature Scaling (fit on train only — prevents data leakage)"""

from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled  = scaler.transform(X_test)

X_train_scaled = pd.DataFrame(X_train_scaled, columns=features)
X_test_scaled  = pd.DataFrame(X_test_scaled,  columns=features)

print("Scaling complete. Feature ranges (train):")
print(X_train_scaled.describe().loc[["min", "max"]])

"""## 7. Baseline ML Models

Three individual (non-ensemble) classifiers trained as baseline comparisons:
- **Logistic Regression** — linear boundary, interpretable, fast
- **Decision Tree** — rule-based splits, interpretable but prone to overfitting
- **K-Nearest Neighbors (KNN)** — distance-based, sensitive to feature scale
"""

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import (
    accuracy_score, precision_score, recall_score,
    f1_score, classification_report, confusion_matrix, ConfusionMatrixDisplay
)
from sklearn.model_selection import cross_val_score

baseline_models = {
    "Logistic Regression": LogisticRegression(max_iter=1000, random_state=42),
    "Decision Tree":       DecisionTreeClassifier(max_depth=8, random_state=42),
    "KNN":                 KNeighborsClassifier(n_neighbors=5)
}

results        = {}
trained_models = {}

for name, model in baseline_models.items():
    model.fit(X_train_scaled, y_train)
    y_pred    = model.predict(X_test_scaled)
    cv_scores = cross_val_score(model, X_train_scaled, y_train, cv=5, scoring="f1_weighted")

    results[name] = {
        "Accuracy":      accuracy_score(y_test, y_pred),
        "Precision":     precision_score(y_test, y_pred, average="weighted", zero_division=0),
        "Recall":        recall_score(y_test, y_pred, average="weighted", zero_division=0),
        "F1 Score":      f1_score(y_test, y_pred, average="weighted", zero_division=0),
        "CV F1 (mean)": cv_scores.mean(),
        "CV F1 (std)":  cv_scores.std()
    }
    trained_models[name] = (model, y_pred)

    print(f"\n{'='*50}\n  {name}\n{'='*50}")
    print(classification_report(y_test, y_pred, zero_division=0))
    print(f"  CV F1: {cv_scores.mean():.4f} ± {cv_scores.std():.4f}")

"""## 8. Ensemble Learning Models

Ensemble methods combine multiple learners to improve performance and reduce overfitting:

- **Random Forest** — Bagging ensemble: trains many independent Decision Trees on random subsets of data and features, then majority-votes. Reduces variance.
- **Gradient Boosting** — Boosting ensemble: trains trees sequentially, each one correcting the errors of the previous. Reduces both bias and variance. Typically outperforms Random Forest on structured data.
"""

from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier

ensemble_models = {
    "Random Forest":      RandomForestClassifier(n_estimators=200, max_depth=10,
                                                  random_state=42, n_jobs=-1),
    "Gradient Boosting":  GradientBoostingClassifier(n_estimators=200, learning_rate=0.1,
                                                      max_depth=5, random_state=42)
}

for name, model in ensemble_models.items():
    model.fit(X_train_scaled, y_train)
    y_pred    = model.predict(X_test_scaled)
    cv_scores = cross_val_score(model, X_train_scaled, y_train, cv=5, scoring="f1_weighted")

    results[name] = {
        "Accuracy":      accuracy_score(y_test, y_pred),
        "Precision":     precision_score(y_test, y_pred, average="weighted", zero_division=0),
        "Recall":        recall_score(y_test, y_pred, average="weighted", zero_division=0),
        "F1 Score":      f1_score(y_test, y_pred, average="weighted", zero_division=0),
        "CV F1 (mean)": cv_scores.mean(),
        "CV F1 (std)":  cv_scores.std()
    }
    trained_models[name] = (model, y_pred)

    print(f"\n{'='*50}\n  {name}\n{'='*50}")
    print(classification_report(y_test, y_pred, zero_division=0))
    print(f"  CV F1: {cv_scores.mean():.4f} ± {cv_scores.std():.4f}")

"""### 8.1 Ensemble — Feature Importance (Random Forest & Gradient Boosting)"""

fig, axes = plt.subplots(1, 2, figsize=(14, 5))

for ax, name in zip(axes, ["Random Forest", "Gradient Boosting"]):
    model = trained_models[name][0]
    importances = pd.Series(model.feature_importances_, index=features).sort_values()
    importances.plot(kind="barh", ax=ax, color="#3498db", edgecolor="black")
    ax.set_title(f"{name} — Feature Importance", fontweight="bold")
    ax.set_xlabel("Importance Score")

plt.suptitle("Feature Importance: Ensemble Models", fontsize=14, fontweight="bold")
plt.tight_layout()
plt.show()

"""## 9. Deep Learning — TabNet

**Why TabNet?**
TabNet (Arik & Pfister, Google, 2021) is specifically designed for **tabular data** — unlike generic DNNs. It uses **sequential attention** to select a sparse subset of features at each decision step, making it:
- Interpretable (shows which features it focuses on per prediction)
- Competitive with tree-based ensembles on structured/environmental data
- More suitable than MLP for this pollution dataset

**Optimization techniques applied:**
- `momentum` and `gamma` in batch normalization (TabNet-specific)
- `lambda_sparse` for feature sparsity regularization
- Early stopping via `patience` parameter
- Learning rate scheduler built into the optimizer

### 9.1 Install & Import TabNet
"""



from pytorch_tabnet.tab_model import TabNetClassifier
import torch

print("PyTorch version:", torch.__version__)
print("CUDA available:", torch.cuda.is_available())

"""### 9.2 Encode Target Labels for TabNet"""

from sklearn.preprocessing import LabelEncoder

le_target = LabelEncoder()
y_train_enc = le_target.fit_transform(y_train.astype(str))
y_test_enc  = le_target.transform(y_test.astype(str))

print("Label encoding:", dict(zip(le_target.classes_, le_target.transform(le_target.classes_))))

"""### 9.3 Build & Train TabNet"""

tabnet = TabNetClassifier(
    n_d              = 32,       # Width of the decision step output
    n_a              = 32,       # Width of the attention embedding
    n_steps          = 5,        # Number of sequential attention steps
    gamma            = 1.5,      # Coefficient for feature reusage across steps
    lambda_sparse    = 1e-4,     # Sparsity regularization — forces focused attention
    optimizer_fn     = torch.optim.Adam,
    optimizer_params = {"lr": 2e-3},
    scheduler_fn     = torch.optim.lr_scheduler.StepLR,
    scheduler_params = {"step_size": 10, "gamma": 0.9},
    mask_type        = 'sparsemax',  # Attention mask — produces sparser, sharper focus
    verbose          = 10
)

X_train_np = X_train_scaled.values.astype(np.float32)
X_test_np  = X_test_scaled.values.astype(np.float32)

tabnet.fit(
    X_train_np, y_train_enc,
    eval_set          = [(X_test_np, y_test_enc)],
    eval_name         = ['test'],
    eval_metric       = ['accuracy'],
    max_epochs        = 100,
    patience          = 15,          # Early stopping: stop if no improvement for 15 epochs
    batch_size        = 256,
    virtual_batch_size= 128
)

print("\nTabNet training complete.")

"""### 9.4 TabNet — Training Curve"""

plt.figure(figsize=(8, 4))
plt.plot(tabnet.history['train_accuracy'], label='Train Accuracy', color='#3498db')
plt.plot(tabnet.history['test_accuracy'],  label='Test Accuracy',  color='#e74c3c')
plt.title("TabNet — Training vs Validation Accuracy", fontweight="bold")
plt.xlabel("Epoch")
plt.ylabel("Accuracy")
plt.legend()
plt.tight_layout()
plt.show()

"""### 9.5 TabNet — Evaluation Metrics"""

y_pred_tabnet_enc = tabnet.predict(X_test_np)
y_pred_tabnet     = le_target.inverse_transform(y_pred_tabnet_enc)

print("TabNet Classification Report:")
print(classification_report(y_test, y_pred_tabnet, zero_division=0))

tabnet_acc  = accuracy_score(y_test, y_pred_tabnet)
tabnet_prec = precision_score(y_test, y_pred_tabnet, average="weighted", zero_division=0)
tabnet_rec  = recall_score(y_test, y_pred_tabnet, average="weighted", zero_division=0)
tabnet_f1   = f1_score(y_test, y_pred_tabnet, average="weighted", zero_division=0)

# Approximate CV using validation accuracy history from training
val_accs       = tabnet.history['test_accuracy']
tabnet_cv_mean = float(np.mean(val_accs))
tabnet_cv_std  = float(np.std(val_accs))

print(f"\nAccuracy : {tabnet_acc:.4f}")
print(f"Precision: {tabnet_prec:.4f}")
print(f"Recall   : {tabnet_rec:.4f}")
print(f"F1 Score : {tabnet_f1:.4f}")

"""### 9.6 TabNet — Feature Attention (Interpretability)"""

# Global feature importance derived from attention masks across all steps
feat_importances = pd.Series(
    tabnet.feature_importances_,
    index=features
).sort_values(ascending=True)

plt.figure(figsize=(8, 5))
feat_importances.plot(kind="barh", color="#8e44ad", edgecolor="black")
plt.title("TabNet — Feature Attention Importance", fontweight="bold")
plt.xlabel("Attention Score (aggregated across steps)")
plt.tight_layout()
plt.show()

print("\nTop features TabNet focused on:")
print(feat_importances.sort_values(ascending=False).head())

"""## 10. Full Model Comparison (ML Baselines + Ensemble + TabNet)

All 6 models compared side by side on the same held-out test set.

### 10.1 Add TabNet to Results & Build Summary Table
"""

results["TabNet (DL)"] = {
    "Accuracy":      tabnet_acc,
    "Precision":     tabnet_prec,
    "Recall":        tabnet_rec,
    "F1 Score":      tabnet_f1,
    "CV F1 (mean)": tabnet_cv_mean,
    "CV F1 (std)":  tabnet_cv_std
}

results_df = pd.DataFrame(results).T.round(4)
results_df = results_df.sort_values("F1 Score", ascending=False)

print("\n📊 Full Model Performance Summary (sorted by F1 Score):")
print(
    results_df.style
    .highlight_max(axis=0, color="#c8f7c5")
    .highlight_min(axis=0, color="#f7c5c5")
)

"""### 10.2 Bar Chart — All Models"""

plot_cols = ["Accuracy", "Precision", "Recall", "F1 Score"]

ax = results_df[plot_cols].plot(
    kind="bar", figsize=(13, 6),
    colormap="Set2", edgecolor="black", linewidth=0.5
)
plt.title("Model Comparison — Baseline ML vs Ensemble vs TabNet (DL)",
          fontsize=13, fontweight="bold")
plt.ylabel("Score")
plt.ylim(0, 1.15)
plt.xticks(rotation=30, ha="right")
plt.legend(loc="lower right")
plt.tight_layout()
plt.show()

"""### 10.3 Cross-Validation Stability Chart"""

fig, ax = plt.subplots(figsize=(9, 5))

model_names = list(results_df.index)
cv_means    = results_df["CV F1 (mean)"].values.astype(float)
cv_stds     = results_df["CV F1 (std)"].values.astype(float)

palette = ["#e74c3c", "#e67e22", "#f1c40f", "#2ecc71", "#3498db", "#9b59b6"]

bars = ax.barh(model_names, cv_means, xerr=cv_stds,
               color=palette[:len(model_names)], edgecolor="black",
               capsize=5, linewidth=0.8)

for bar, val in zip(bars, cv_means):
    ax.text(val + 0.005, bar.get_y() + bar.get_height()/2,
            f"{val:.3f}", va='center', fontsize=9)

ax.set_xlabel("Weighted F1 Score (CV / Validation)")
ax.set_title("Model Stability — CV F1 with Error Bars", fontweight="bold")
ax.set_xlim(0, 1.05)
plt.tight_layout()
plt.show()

"""### 10.4 Confusion Matrices — All Models"""

# Add TabNet to trained_models dict for unified plotting
trained_models["TabNet (DL)"] = (tabnet, y_pred_tabnet)

n_models    = len(trained_models)
n_cols      = 3
n_rows      = (n_models + n_cols - 1) // n_cols
class_labels = ["Low", "Medium", "High"]

fig, axes = plt.subplots(n_rows, n_cols, figsize=(16, 10))
axes = axes.flatten()

for i, (name, (model, y_pred)) in enumerate(trained_models.items()):
    pred = y_pred if name != "TabNet (DL)" else y_pred_tabnet
    cm   = confusion_matrix(y_test, pred, labels=class_labels)
    disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=class_labels)
    disp.plot(ax=axes[i], colorbar=False, cmap="Blues")
    axes[i].set_title(name, fontsize=11, fontweight="bold")

# Hide any unused subplot slots
for j in range(i + 1, len(axes)):
    axes[j].set_visible(False)

plt.suptitle("Confusion Matrices — All Models", fontsize=14, fontweight="bold", y=1.02)
plt.tight_layout()
plt.show()

"""### 10.5 Best Model & Justification"""

best_model_name = results_df["F1 Score"].idxmax()
best_score      = results_df.loc[best_model_name, "F1 Score"]

print("=" * 55)
print(f"  🏆 Best Model : {best_model_name}")
print(f"  Weighted F1  : {best_score:.4f}")
print("=" * 55)
print()
print("Full metrics for best model:")
print(results_df.loc[best_model_name])
print()
print("Why TabNet performs well here:")
print("  • Attention mechanism selects the most relevant pollutants per prediction")
print("  • Sparsity regularization prevents overfitting on the tabular feature set")
print("  • Sequential multi-step reasoning captures non-linear pollutant interactions")
print("  • Early stopping + LR scheduler prevent overfitting during training")

"""## 11. Green Infrastructure Recommendation System

Based on `Pollution_Zone` and geographic location, each area receives a targeted green solution:

| Zone   | Location Context         | Recommendation                    |
|--------|--------------------------|-----------------------------------|
| High   | Urban / Dense (high loc) | Green Walls + Vertical Gardens    |
| High   | Peripheral               | Urban Forest + Dense Plantation   |
| Medium | Any                      | Roadside Trees + Green Roofs      |
| Low    | Any                      | Maintain Existing Greenery        |
"""

df_clean = df_clean.copy()
df_clean["Location_Score"] = df_clean["lat"] + df_clean["long"]
location_median = df_clean["Location_Score"].median()

def recommend_green_solution(row):
    zone = row["Pollution_Zone"]
    loc  = row["Location_Score"]

    if zone == "High":
        return "Green Walls + Vertical Gardens" if loc > location_median \
               else "Urban Forest + Dense Plantation"
    elif zone == "Medium":
        return "Roadside Trees + Green Roofs"
    else:
        return "Maintain Existing Greenery"

df_clean["Recommendation"] = df_clean.apply(recommend_green_solution, axis=1)

print("Recommendation Distribution:")
print(df_clean["Recommendation"].value_counts())

"""### 11.1 Recommendation Distribution Plot"""

palette = {
    "Green Walls + Vertical Gardens":  "#8e44ad",
    "Urban Forest + Dense Plantation": "#27ae60",
    "Roadside Trees + Green Roofs":    "#f39c12",
    "Maintain Existing Greenery":      "#2ecc71"
}

rec_counts = df_clean["Recommendation"].value_counts()
colors     = [palette.get(r, "#95a5a6") for r in rec_counts.index]

plt.figure(figsize=(9, 5))
rec_counts.plot(kind="barh", color=colors, edgecolor="black")
plt.title("🌿 Green Infrastructure Recommendations by Area Count", fontsize=13)
plt.xlabel("Number of Areas")
plt.tight_layout()
plt.show()

"""### 11.2 Sample Output"""

output_cols = ["AQIValue", "PM2.5", "PM10", "NO2", "Pollution_Zone", "Recommendation"]
available   = [c for c in output_cols if c in df_clean.columns]

print(df_clean[available].head(15))

"""### 11.3 Save Results"""

df_clean[available].to_excel("pollution_hotspots_recommendations.xlsx", index=False)
results_df.to_excel("model_comparison_results.xlsx")

print("✅ Saved: pollution_hotspots_recommendations.xlsx")
print("✅ Saved: model_comparison_results.xlsx")