# -*- coding: utf-8 -*-
"""mlfinal.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HOydJohziMi2uym1fHo16c7VVbgZOxVH

#  Urban Pollution Hotspot Identification & Green Infrastructure Recommendation

**Objective:** Classify areas into pollution zones (Low / Medium / High) using air quality features, then recommend appropriate green solutions such as trees, green roofs, urban parks, and vertical gardens.

**Pipeline Overview:**
1. Data Loading & Inspection
2. Data Preprocessing (cleaning, encoding, outlier handling)
3. Feature Engineering
4. Exploratory Data Analysis (EDA)
5. Target Variable Creation (before scaling)
6. Feature Scaling & Train-Test Split
7. Baseline Model Training & Evaluation
8. Model Comparison
9. Green Infrastructure Recommendation System

## 1. Data Loading & Initial Inspection
"""

import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')
from IPython.display import display

df = pd.read_excel(r"C:\Users\bhava\Downloads\MLfeb8.xlsx")

print("Shape:", df.shape)
print("\nFirst 5 rows:")
display(df.head())
print("\nData Types & Null Counts:")
df.info()

"""## 2. Data Preprocessing

### 2.1 Convert Pollutant Columns to Numeric
"""

pollutant_cols = ["SO2", "NO2", "CO", "PM2.5", "PM10", "AQIValue"]

for col in pollutant_cols:
    df[col] = pd.to_numeric(df[col], errors="coerce")

print("Null counts after conversion:")
print(df[pollutant_cols].isnull().sum())

"""### 2.2 Handle Missing Values (Mean Imputation)"""

for col in pollutant_cols:
    df[col] = df[col].fillna(df[col].mean())

print("Null counts after imputation:")
print(df[pollutant_cols].isnull().sum())

"""### 2.3 Parse Dates & Extract Date Features"""

df["Date"] = pd.to_datetime(df["Date"], dayfirst=True)

df["year"]    = df["Date"].dt.year
df["month"]   = df["Date"].dt.month
df["day"]     = df["Date"].dt.day
df["weekday"] = df["Date"].dt.weekday

# Drop year if it has no variation (single-year datasets add no information)
if df["year"].nunique() == 1:
    df = df.drop("year", axis=1)
    print("'year' dropped — only one unique value found.")

print(df[["month", "day", "weekday"]].head())

"""### 2.4 Label Encoding for Prominent Pollutant"""

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
if "ProminentPollutant" in df.columns:
    df["ProminentPollutant_encoded"] = le.fit_transform(df["ProminentPollutant"].astype(str))
    print("ProminentPollutant classes:", le.classes_)

"""## 3. Feature Engineering

### 3.1 Composite Pollution Index

A weighted combination of major pollutants representing overall pollution load.
"""

df["Pollution_Index"] = (
    df["PM2.5"] * 0.4 +
    df["PM10"]  * 0.3 +
    df["NO2"]   * 0.1 +
    df["SO2"]   * 0.1 +
    df["CO"]    * 0.1
)

print("Pollution_Index stats:")
print(df["Pollution_Index"].describe())

"""## 4. Exploratory Data Analysis (EDA)

### 4.1 Correlation Heatmap
"""

import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(12, 10))
sns.heatmap(
    df.corr(numeric_only=True),
    annot=True, cmap="coolwarm", fmt=".2f"
)
plt.title("Correlation Matrix (All Numeric Features)")
plt.tight_layout()
plt.show()

"""### 4.2 Feature Correlation with AQI"""

corr_aqi = df.corr(numeric_only=True)["AQIValue"].drop("AQIValue").sort_values()

plt.figure(figsize=(8, 6))
colors = ["#d73027" if v > 0 else "#4575b4" for v in corr_aqi]
corr_aqi.plot(kind="barh", color=colors)
plt.axvline(0, color="black", linewidth=0.8)
plt.title("Feature Correlation with AQI Value")
plt.xlabel("Pearson Correlation")
plt.tight_layout()
plt.show()

"""### 4.3 AQI Distribution"""

plt.figure(figsize=(8, 4))
sns.histplot(df["AQIValue"], bins=40, kde=True, color="steelblue")
plt.title("Distribution of AQI Values")
plt.xlabel("AQI Value")
plt.tight_layout()
plt.show()

print(df["AQIValue"].describe())

"""## 5. Target Variable Creation

> ⚠️ **Important:** The target variable `Pollution_Zone` is created from the **raw (unscaled) AQI values** using meaningful breakpoints. Scaling happens *after* this step to avoid ambiguous bins on a 0–1 range.
"""

# Outlier clipping before binning (IQR method on raw AQI)
for col in ["PM2.5", "PM10", "NO2", "AQIValue"]:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    df[col] = df[col].clip(Q1 - 1.5 * IQR, Q3 + 1.5 * IQR)

print("AQI range after clipping:", df["AQIValue"].min(), "–", df["AQIValue"].max())

# Create Pollution Zone using AQI percentiles for robust binning
low_cut  = df["AQIValue"].quantile(0.33)
high_cut = df["AQIValue"].quantile(0.66)

print(f"\nBin thresholds — Low < {low_cut:.1f} | Medium: {low_cut:.1f}–{high_cut:.1f} | High > {high_cut:.1f}")

df["Pollution_Zone"] = pd.cut(
    df["AQIValue"],
    bins=[df["AQIValue"].min() - 1, low_cut, high_cut, df["AQIValue"].max()],
    labels=["Low", "Medium", "High"],
    include_lowest=True
)

print("\nClass distribution:")
print(df["Pollution_Zone"].value_counts())

# Plot class balance
plt.figure(figsize=(6, 4))
df["Pollution_Zone"].value_counts().plot(kind="bar", color=["#2ecc71", "#f39c12", "#e74c3c"])
plt.title("Pollution Zone Class Distribution")
plt.xlabel("Zone")
plt.ylabel("Count")
plt.xticks(rotation=0)
plt.tight_layout()
plt.show()

"""## 6. Feature Selection, Scaling & Train-Test Split

### 6.1 Drop Low-Impact & Redundant Features
"""

# Drop: encoded pollutant (low AQI correlation), raw text column, CO and SO2 (low variance/correlation)
cols_to_drop = ["ProminentPollutant_encoded", "ProminentPollutant", "CO", "SO2", "Date"]
df = df.drop(cols_to_drop, axis=1, errors="ignore")

print("Remaining columns:", list(df.columns))

"""### 6.2 Define Features & Target"""

features = ["PM2.5", "PM10", "NO2", "Pollution_Index", "lat", "long", "month"]

  # Keep only features that exist in df
features = [f for f in features if f in df.columns]
print("Selected features:", features)

  # Drop rows with any NaN in features or target
df_clean = df.dropna(subset=features + ["Pollution_Zone"]).copy()
print(f"\nRows before cleaning: {len(df)} | After cleaning: {len(df_clean)}")

X = df_clean[features]
y = df_clean["Pollution_Zone"]

"""### 6.3 Train-Test Split (before scaling to prevent data leakage)"""

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

print(f"Training samples: {len(X_train)} | Test samples: {len(X_test)}")
print("\nClass balance in train:")
print(y_train.value_counts())

"""### 6.4 Feature Scaling (fit on train, transform both)"""

from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

# Fit ONLY on training data — transform both sets
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled  = scaler.transform(X_test)

# Convert back to DataFrames for readability
X_train_scaled = pd.DataFrame(X_train_scaled, columns=features)
X_test_scaled  = pd.DataFrame(X_test_scaled,  columns=features)

print("Scaling complete. Feature ranges (train):")
print(X_train_scaled.describe().loc[["min", "max"]])

"""## 7. Baseline Model Training & Evaluation

Four baseline classifiers are trained and compared:
- **Logistic Regression** — linear boundary, interpretable
- **Decision Tree** — rule-based, prone to overfitting
- **Random Forest** — ensemble of trees, robust
- **K-Nearest Neighbors (KNN)** — distance-based, sensitive to scale
"""

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import (
    accuracy_score, precision_score, recall_score,
    f1_score, classification_report, confusion_matrix, ConfusionMatrixDisplay
)
from sklearn.model_selection import cross_val_score

models = {
    "Logistic Regression": LogisticRegression(max_iter=1000, random_state=42),
    "Decision Tree":       DecisionTreeClassifier(random_state=42),
    "Random Forest":       RandomForestClassifier(n_estimators=100, random_state=42),
    "KNN":                 KNeighborsClassifier(n_neighbors=5)
}

results      = {}
trained_models = {}

for name, model in models.items():
    # Train
    model.fit(X_train_scaled, y_train)
    y_pred = model.predict(X_test_scaled)

    # Cross-validation (5-fold) on training set
    cv_scores = cross_val_score(model, X_train_scaled, y_train, cv=5, scoring="f1_weighted")

    results[name] = {
        "Accuracy":      accuracy_score(y_test, y_pred),
        "Precision":     precision_score(y_test, y_pred, average="weighted", zero_division=0),
        "Recall":        recall_score(y_test, y_pred, average="weighted", zero_division=0),
        "F1 Score":      f1_score(y_test, y_pred, average="weighted", zero_division=0),
        "CV F1 (mean)": cv_scores.mean(),
        "CV F1 (std)":  cv_scores.std()
    }

    trained_models[name] = (model, y_pred)

    print(f"\n{'='*50}")
    print(f"  {name}")
    print(f"{'='*50}")
    print(classification_report(y_test, y_pred, zero_division=0))
    print(f"  CV F1: {cv_scores.mean():.4f} ± {cv_scores.std():.4f}")

"""## 8. Model Comparison

### 8.1 Performance Summary Table
"""

results_df = pd.DataFrame(results).T.round(4)
results_df = results_df.sort_values("F1 Score", ascending=False)

print("Model Performance Summary (sorted by F1 Score):")
display(results_df.style.highlight_max(axis=0, color="#c8f7c5").highlight_min(axis=0, color="#f7c5c5"))

"""### 8.2 Bar Chart Comparison"""

plot_cols = ["Accuracy", "Precision", "Recall", "F1 Score"]

ax = results_df[plot_cols].plot(
    kind="bar", figsize=(11, 6),
    colormap="Set2", edgecolor="black", linewidth=0.5
)
plt.title("Baseline Model Comparison — Test Set Metrics", fontsize=14, fontweight="bold")
plt.ylabel("Score")
plt.ylim(0, 1.1)
plt.xticks(rotation=30, ha="right")
plt.legend(loc="lower right")
plt.tight_layout()
plt.show()

"""### 8.3 Cross-Validation F1 Comparison"""

fig, ax = plt.subplots(figsize=(8, 5))

model_names = list(results_df.index)
cv_means    = results_df["CV F1 (mean)"].values
cv_stds     = results_df["CV F1 (std)"].values

colors = ["#2ecc71", "#3498db", "#e74c3c", "#f39c12"]

ax.barh(model_names, cv_means, xerr=cv_stds,
        color=colors[:len(model_names)], edgecolor="black",
        capsize=5, linewidth=0.8)
ax.set_xlabel("Weighted F1 Score (5-Fold CV)")
ax.set_title("Cross-Validation F1 Score with Std Dev")
ax.set_xlim(0, 1.0)
plt.tight_layout()
plt.show()

"""### 8.4 Confusion Matrices for All Models"""

fig, axes = plt.subplots(2, 2, figsize=(14, 10))
axes = axes.flatten()

class_labels = ["Low", "Medium", "High"]

for i, (name, (model, y_pred)) in enumerate(trained_models.items()):
    cm = confusion_matrix(y_test, y_pred, labels=class_labels)
    disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=class_labels)
    disp.plot(ax=axes[i], colorbar=False, cmap="Blues")
    axes[i].set_title(f"{name}", fontsize=12, fontweight="bold")

plt.suptitle("Confusion Matrices — All Baseline Models", fontsize=14, fontweight="bold", y=1.02)
plt.tight_layout()
plt.show()

"""### 8.5 Best Model Summary

Identify the best performing model based on F1 Score.
"""

best_model_name = results_df["F1 Score"].idxmax()
best_score      = results_df.loc[best_model_name, "F1 Score"]

print(f" Best Model: {best_model_name}")
print(f"   Weighted F1 Score: {best_score:.4f}")
print()
print("Full metrics:")
print(results_df.loc[best_model_name])

"""## 9. Green Infrastructure Recommendation System

Based on predicted `Pollution_Zone` and geographic location (latitude + longitude), each area is assigned a targeted green solution:

| Zone   | Location Context    | Recommendation                     |
|--------|---------------------|------------------------------------|
| High   | Dense/urban (high lat+long score) | Green Walls + Vertical Gardens |
| High   | Peripheral          | Urban Forest + Dense Plantation    |
| Medium | Any                 | Roadside Trees + Green Roofs       |
| Low    | Any                 | Maintain Existing Greenery         |
"""

# Compute Location Score on the full clean dataset (raw lat/long, not scaled)
df_clean = df_clean.copy()
df_clean["Location_Score"] = df_clean["lat"] + df_clean["long"]
location_median = df_clean["Location_Score"].median()

def recommend_green_solution(row):
    zone = row["Pollution_Zone"]
    loc  = row["Location_Score"]

    if zone == "High":
        if loc > location_median:
            return "Green Walls + Vertical Gardens"
        else:
            return "Urban Forest + Dense Plantation"
    elif zone == "Medium":
        return "Roadside Trees + Green Roofs"
    else:  # Low
        return "Maintain Existing Greenery"

df_clean["Recommendation"] = df_clean.apply(recommend_green_solution, axis=1)

print("Recommendation Distribution:")
print(df_clean["Recommendation"].value_counts())

"""### 9.1 Recommendation Distribution Plot"""

palette = {
    "Green Walls + Vertical Gardens":   "#8e44ad",
    "Urban Forest + Dense Plantation":  "#27ae60",
    "Roadside Trees + Green Roofs":     "#f39c12",
    "Maintain Existing Greenery":       "#2ecc71"
}

rec_counts = df_clean["Recommendation"].value_counts()
colors = [palette.get(r, "#95a5a6") for r in rec_counts.index]

plt.figure(figsize=(9, 5))
rec_counts.plot(kind="barh", color=colors, edgecolor="black")
plt.title(" Green Infrastructure Recommendations by Area Count", fontsize=13)
plt.xlabel("Number of Areas")
plt.tight_layout()
plt.show()

"""### 9.2 Sample Output — Pollution Zones & Recommendations"""

output_cols = ["AQIValue", "PM2.5", "PM10", "NO2", "Pollution_Zone", "Recommendation"]
available   = [c for c in output_cols if c in df_clean.columns]

display(df_clean[available].head(15))

"""### 9.3 Save Final Results to Excel"""

df_clean[available].to_excel("pollution_hotspots_recommendations.xlsx", index=False)
print("✅ Results saved to 'pollution_hotspots_recommendations.xlsx'")

from sklearn.preprocessing import LabelEncoder

le_target = LabelEncoder()
y_train_enc = le_target.fit_transform(y_train)
y_test_enc  = le_target.transform(y_test)

print(le_target.classes_)  # ['High', 'Low', 'Medium'] (order may vary)

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout

model = Sequential()

# Input layer
model.add(Dense(64, activation='relu', input_shape=(X_train_scaled.shape[1],)))

# Hidden layers
model.add(Dense(128, activation='relu'))
model.add(Dropout(0.3))

model.add(Dense(64, activation='relu'))
model.add(Dropout(0.3))

# Output layer (3 classes)
model.add(Dense(3, activation='softmax'))

# Compile
model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

model.summary()

history = model.fit(
    X_train_scaled, y_train_enc,
    validation_split=0.2,
    epochs=20,
    batch_size=32,
    verbose=1
)

from sklearn.metrics import classification_report

# Predictions
y_pred_probs = model.predict(X_test_scaled)
y_pred = y_pred_probs.argmax(axis=1)

# Convert back to labels
y_pred_labels = le_target.inverse_transform(y_pred)

print(classification_report(y_test, y_pred_labels))

from sklearn.metrics import accuracy_score, f1_score

dl_accuracy = accuracy_score(y_test, y_pred_labels)
dl_f1 = f1_score(y_test, y_pred_labels, average='weighted')

print("Deep Learning Model:")
print("Accuracy:", dl_accuracy)
print("F1 Score:", dl_f1)